name: ${APP_NAME}-${APP_MODE}

services:
  mongodb:
    image: mongo:7.0
    container_name: ${APP_NAME}-${APP_MODE}-mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - database:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: ${APP_NAME}-${APP_MODE}

volumes:
  database:
    name: ${APP_NAME}-database-${APP_MODE}
